### ISSUE TITLE
IPB 3.4

### ISSUE THREAD

**Issue by AndrewRAN** [FmWebStudio/IPS-Submit-By-Ctrl-Enter#1]
Please, make a version of your plug-in for IPB 3.4, **PLEASE!!!**

**Comment by Recouse** [comment]
Hello.
I'm sorry, but IPB 3.4 no longer supported by IPS and other developers.

**Comment by AndrewRAN** [comment]
Oooh :(

**Comment by Recouse** [comment]
You can find IPB 3.4 developers here http://ipbskins.ru/forum/forum20.html
